'use client';
import {useState} from 'react';
export type GroupFriend={id:string;displayName:string;elo:number;favorite:boolean;groupName:string;presence:string};
export default function FriendGroups({friends,onChange,onRemove}:{friends:GroupFriend[];onChange:()=>Promise<void>;onRemove:(id:string)=>void}) {
  const [editing,setEditing]=useState<string|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const groups=[...new Set(friends.filter(f=>!f.favorite).map(f=>f.groupName))].sort((a,b)=>a.localeCompare(b,'ko'));
  async function save(f:GroupFriend,favorite:boolean,groupName:string){setBusy(true);setError('');try{const r=await fetch('/api/friends',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'organize',userId:f.id,favorite,groupName})});if(!r.ok)throw new Error('친구 설정을 저장하지 못했습니다.');await onChange();setEditing(null);}catch(e){setError(e instanceof Error?e.message:'연결 오류');}finally{setBusy(false);}}
  function group(title:string,items:GroupFriend[]){return <section key={title} className="friend-group"><h3>{title} <b>{items.length}</b></h3>{!items.length?<p>즐겨찾기한 친구가 없습니다.</p>:<ul>{items.map(f=><li key={f.id}><div><strong>{f.displayName}</strong><span className={f.presence==='오프라인'?'friend-offline':'friend-online'}>{f.presence} · {f.elo} ELO</span></div><div className="friend-actions"><button disabled={busy} aria-label={`${f.displayName} 즐겨찾기`} aria-pressed={f.favorite} onClick={()=>void save(f,!f.favorite,f.groupName)}>{f.favorite?'★':'☆'}</button><button disabled={busy} onClick={()=>{setEditing(f.id);setName(f.groupName);}}>그룹</button><button disabled={busy} onClick={()=>onRemove(f.id)}>삭제</button></div>{editing===f.id&&<form className="friend-group-editor" onSubmit={e=>{e.preventDefault();void save(f,f.favorite,name);}}><label htmlFor={`group-${f.id}`}>그룹 이름</label><input id={`group-${f.id}`} maxLength={20} value={name} onChange={e=>setName(e.target.value)} placeholder="비우면 기본 그룹"/><button disabled={busy}>저장</button><button type="button" onClick={()=>setEditing(null)}>취소</button></form>}</li>)}</ul>}</section>;}
  return <div>{error&&<p role="alert">{error}</p>}{group('즐겨찾기',friends.filter(f=>f.favorite))}{groups.map(g=>group(g||'기본',friends.filter(f=>!f.favorite&&f.groupName===g)))}<small>접속 상태는 최근 90초 연결 기준입니다.</small></div>;
}
