'use client';

import { useEffect, useMemo, useState } from 'react';
import { RotateCcw, Sparkles, Volume2, VolumeX } from 'lucide-react';
declare global { interface Document { modelContext?: { registerTool(tool: unknown, options?: { signal?: AbortSignal }): void | Promise<void> } } }
type Side = 'cho' | 'han';
type Piece = { id:string; label:string; side:Side; x:number; y:number; kind:string };
const opening:Piece[]=[
{id:'hk',label:'漢',side:'han',x:4,y:1,kind:'궁'},{id:'hr1',label:'車',side:'han',x:0,y:0,kind:'차'},{id:'hr2',label:'車',side:'han',x:8,y:0,kind:'차'},{id:'hc1',label:'包',side:'han',x:1,y:2,kind:'포'},{id:'hc2',label:'包',side:'han',x:7,y:2,kind:'포'},{id:'hs1',label:'卒',side:'han',x:0,y:3,kind:'졸'},{id:'hs2',label:'卒',side:'han',x:2,y:3,kind:'졸'},{id:'hs3',label:'卒',side:'han',x:4,y:3,kind:'졸'},{id:'hs4',label:'卒',side:'han',x:6,y:3,kind:'졸'},{id:'hs5',label:'卒',side:'han',x:8,y:3,kind:'졸'},
{id:'ck',label:'楚',side:'cho',x:4,y:8,kind:'궁'},{id:'cr1',label:'車',side:'cho',x:0,y:9,kind:'차'},{id:'cr2',label:'車',side:'cho',x:8,y:9,kind:'차'},{id:'cc1',label:'炮',side:'cho',x:1,y:7,kind:'포'},{id:'cc2',label:'炮',side:'cho',x:4,y:5,kind:'포'},{id:'cs1',label:'兵',side:'cho',x:0,y:6,kind:'병'},{id:'cs2',label:'兵',side:'cho',x:2,y:6,kind:'병'},{id:'cs3',label:'兵',side:'cho',x:4,y:6,kind:'병'},{id:'cs4',label:'兵',side:'cho',x:6,y:6,kind:'병'},{id:'cs5',label:'兵',side:'cho',x:8,y:6,kind:'병'}];

export default function Home(){
 const [pieces,setPieces]=useState(opening),[selected,setSelected]=useState<string|null>('cc2'),[turn,setTurn]=useState<Side>('cho'),[cinema,setCinema]=useState(true),[sound,setSound]=useState(true),[impact,setImpact]=useState<{x:number;y:number;label:string}|null>(null),[status,setStatus]=useState('포를 선택했습니다. 빛나는 지점을 눌러보세요.');
 const selectedPiece=pieces.find(p=>p.id===selected);
 const targets=useMemo(()=>{if(!selectedPiece)return[];if(selectedPiece.id==='cc2')return[{x:4,y:3},{x:4,y:2},{x:4,y:1}];return [[0,-1],[0,1],[-1,0],[1,0]].map(([dx,dy])=>({x:selectedPiece.x+dx,y:selectedPiece.y+dy})).filter(({x,y})=>x>=0&&x<=8&&y>=0&&y<=9)},[selectedPiece]);
 useEffect(()=>{if(!impact)return;const t=window.setTimeout(()=>setImpact(null),900);return()=>window.clearTimeout(t)},[impact]);
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'reset_janggi_match',title:'장기 대국 다시 두기',description:'현재 연출 프로토타입을 처음 상태로 되돌립니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){setPieces(opening);setSelected('cc2');setTurn('cho');setImpact(null);setStatus('포를 선택했습니다. 빛나는 지점을 눌러보세요.');return{status:'reset',turn:'cho'}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 function choose(p:Piece){if(p.side!==turn)return;setSelected(p.id);setStatus(`${p.kind} 선택 — 이동할 교차점을 고르세요.`)}
 function move(x:number,y:number){if(!selectedPiece||!targets.some(t=>t.x===x&&t.y===y))return;const victim=pieces.find(p=>p.x===x&&p.y===y&&p.side!==selectedPiece.side);setPieces(c=>c.filter(p=>!victim||p.id!==victim.id).map(p=>p.id===selectedPiece.id?{...p,x,y}:p));if(victim){setImpact({x,y,label:victim.kind==='궁'?'장군!':'격파'});setStatus(victim.kind==='궁'?'장군! 궁성이 흔들립니다.':`${selectedPiece.kind}로 ${victim.kind}을 잡았습니다.`)}else setStatus(`${selectedPiece.kind} 이동 완료.`);setSelected(null);setTurn(turn==='cho'?'han':'cho')}
 function reset(){setPieces(opening);setSelected('cc2');setTurn('cho');setImpact(null);setStatus('포를 선택했습니다. 빛나는 지점을 눌러보세요.')}
 return <main className={`game-shell ${impact&&cinema?'screen-impact':''}`}>
  <header className="topbar"><div className="brand"><span className="brand-mark"><i>將</i></span><span>장기: 격돌</span><em>PROTOTYPE 01</em></div><div className="header-actions"><button className={`icon-btn ${cinema?'active':''}`} onClick={()=>setCinema(!cinema)} aria-label="연출 효과 전환"><Sparkles size={18}/></button><button className="icon-btn" onClick={()=>setSound(!sound)} aria-label="소리 전환">{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="text-btn" onClick={reset}><RotateCcw size={15}/> 다시 두기</button></div></header>
  <section className="match-layout"><Player side="han" active={turn==='han'}/><div className="arena"><div className="turn-indicator"><span className={turn}/>{turn==='cho'?'초의 차례':'한의 차례'}</div><div className="board-frame"><div className="board" role="grid" aria-label="장기판 연출 프로토타입"><div className="river-mark">楚 河　　漢 界</div><div className="palace palace-top"/><div className="palace palace-bottom"/>{targets.map(t=><button key={`${t.x}-${t.y}`} className="move-target" onClick={()=>move(t.x,t.y)} aria-label={`${t.x+1}열 ${t.y+1}행으로 이동`} style={{left:`${t.x*12.5}%`,top:`${t.y*(100/9)}%`}}/>)}{pieces.map(p=><button key={p.id} onClick={()=>choose(p)} className={`piece ${p.side} ${selected===p.id?'selected':''}`} style={{left:`${p.x*12.5}%`,top:`${p.y*(100/9)}%`}} aria-label={`${p.side==='cho'?'초':'한'} ${p.kind}`}><span>{p.label}</span></button>)}{impact&&<div className="impact" style={{left:`${impact.x*12.5}%`,top:`${impact.y*(100/9)}%`}}><i/><b>{impact.label}</b></div>}</div></div><div className="status-strip"><span className="status-dot"/><p>{status}</p><kbd>CLICK</kbd></div></div><Player side="cho" active={turn==='cho'}/></section>
  <footer><span>연출 강도 <b>{cinema?'시네마틱':'절제'}</b></span><span className="hint"><Sparkles size={14}/> 포로 중앙의 졸을 잡아보세요</span><span>포획 <b>{20-pieces.length}</b></span></footer>
 </main>
}
function Player({side,active}:{side:Side;active:boolean}){const cho=side==='cho';return <aside className={`player-card ${side}-card`}><div><span className="side-label">{cho?'푸른 진영':'붉은 진영'}</span><h2>{cho?'초 · 楚':'한 · 漢'}</h2></div><div className={`avatar ${side}-avatar`}>{cho?'楚':'漢'}</div><div className={`clock ${active?'active-clock':''}`}>{cho?'10:00':'09:42'}</div><p>{active?'당신의 차례입니다':'상대가 생각하는 중'}</p></aside>}
